- alias: Notify - Smoke detected
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'Warning'
      entity_id:
        - sensor.downstairs_nest_protect_smoke_status
        - sensor.upstairs_nest_protect_smoke_status
    - platform: state
      to: 'Emergency'
      entity_id:
        - sensor.downstairs_nest_protect_smoke_status
        - sensor.upstairs_nest_protect_smoke_status
  action:
    service: notify.ios_Geoff
    data:
      message: "Smoke detected at home!!"



- alias: Notify - Smoke cleared
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'Ok'
      entity_id:
        - sensor.downstairs_nest_protect_smoke_status
        - sensor.upstairs_nest_protect_smoke_status
  action:
    service: notify.ios_Geoff
    data:
      message: "Smoke has cleared at home"



- alias: Notify - Carbon monoxide detected
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'Warning'
      entity_id:
        - sensor.downstairs_nest_protect_co_status
        - sensor.upstairs_nest_protect_co_status
    - platform: state
      to: 'Emergency'
      entity_id:
        - sensor.downstairs_nest_protect_co_status
        - sensor.upstairs_nest_protect_co_status
  action:
    service: notify.ios_Geoff
    data:
      message: "Carbon monoxide detected at home!!"



- alias: Notify - Carbon monoxide cleared
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'Ok'
      entity_id:
        - sensor.downstairs_nest_protect_co_status
        - sensor.upstairs_nest_protect_co_status
  action:
    service: notify.ios_Geoff
    data:
      message: "Carbon monoxide has cleared at home"



- alias: Notify - Nest battery warning
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'Warning'
      entity_id:
        - sensor.downstairs_nest_protect_battery_health
        - sensor.upstairs_nest_protect_battery_health
    - platform: state
      to: 'Emergency'
      entity_id:
        - sensor.downstairs_nest_protect_battery_health
        - sensor.upstairs_nest_protect_battery_health
  action:
    service: notify.ios_Geoff
    data:
      message: "Nest protect has a battery issue!"



- alias: Notify - Nest battery ok
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'Ok'
      entity_id:
        - sensor.downstairs_nest_protect_battery_health
        - sensor.upstairs_nest_protect_battery_health
  action:
    service: notify.ios_Geoff
    data:
      message: "Nest protect battery is now ok."



- alias: Notify - Nest offline
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'Off'
      entity_id:
        - binary_sensor.downstairs_nest_protect_online
        - binary_sensor.upstairs_nest_protect_online
  action:
    service: notify.ios_Geoff
    data:
      message: "A Nest device has gone offline."



- alias: Notify - Nest online
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'On'
      entity_id:
        - binary_sensor.downstairs_nest_protect_online
        - binary_sensor.upstairs_nest_protect_online
  action:
    service: notify.ios_Geoff
    data:
      message: "Nest device has reconnected."



- alias: Kitchen Lamp - On at sunset
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.tplink_switch



- alias: Kitchen Lamp - Off at night
  initial_state: 'on'
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.tplink_switch

    

- alias: Heating - Mornings
  initial_state: 'on'
  trigger:
  - platform: time
    at: '05:30:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.met_office_temperature
    below: '10'
  action:
    - service: switch.turn_on
      entity_id: switch.heating
    - delay: '02:00:00'
    - service: switch.turn_off
      entity_id: switch.heating



- alias: Heating - Evenings
  initial_state: 'on'
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.met_office_temperature
    below: '10'
  action:
    - service: switch.turn_on
      entity_id: switch.heating
    - delay: '03:00:00'
    - service: switch.turn_off
      entity_id: switch.heating



- alias: Heating - Weekends
  initial_state: 'on'
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.met_office_temperature
        below: '10'
      - condition: time
        weekday:
          - sat
          - sun
  action:
    - service: switch.turn_on
      entity_id: switch.heating
    - delay: '05:00:00'
    - service: switch.turn_off
      entity_id: switch.heating



- alias: Heating - Boost off
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'off'
      entity_id: input_boolean.heating_boost
  action:
    - service: switch.turn_off
      entity_id: switch.heating



- alias: Heating - Boost on
  initial_state: 'on'
  trigger:
    - platform: state
      to: 'on'
      entity_id: input_boolean.heating_boost
  action:
    - service: switch.turn_on
      entity_id: switch.heating
    - delay: '02:00:00'
    - service: switch.turn_off
      entity_id: switch.heating
    - service: input_boolean.turn_off
      entity_id: input_boolean.heating_boost
