- alias: Notify - Geoff Commute Time
  trigger:
    - platform: time
      at: '07:30:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.geoff_commute
        above: '39'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    service: notify.mobile_app_gef_tactics
    data:
      message: "Commute time is currently {{ states.sensor.geoff_commute.state }} minutes."
