- alias: Ellies Lamp - On at sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.ellies_lamp


- alias: Ellies Lamp - Off in morning
  trigger:
    platform: time
    at: '08:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.ellies_lamp

