- alias: Ellies Room - On at bedtime
  trigger:
    platform: time
    at: "19:30:00"
  action:
    service: homeassistant.turn_on
    entity_id: light.upstairs_light


- alias: Ellies Room - Off in the night
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.upstairs_light


- alias: Ellies Room - Off in morning
  trigger:
    platform: time
    at: '08:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.upstairs_light

