- alias: Heating - Mornings
  trigger:
  - platform: time
    at: '05:30:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.met_office_temperature
    below: '10'
  action:
    - service: switch.turn_on
      entity_id: switch.heating
    - delay: '02:00:00'
    - service: switch.turn_off
      entity_id: switch.heating



- alias: Heating - Evenings
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.met_office_temperature
    below: '10'
  action:
    - service: switch.turn_on
      entity_id: switch.heating
    - delay: '03:00:00'
    - service: switch.turn_off
      entity_id: switch.heating



- alias: Heating - Weekends
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.met_office_temperature
        below: '10'
      - condition: time
        weekday:
          - sat
          - sun
  action:
    - service: switch.turn_on
      entity_id: switch.heating
    - delay: '05:00:00'
    - service: switch.turn_off
      entity_id: switch.heating



- alias: Heating - Boost off
  trigger:
    - platform: state
      to: 'off'
      entity_id: input_boolean.heating_boost
  action:
    - service: switch.turn_off
      entity_id: switch.heating



- alias: Heating - Boost on
  trigger:
    - platform: state
      to: 'on'
      entity_id: input_boolean.heating_boost
  action:
    - service: switch.turn_on
      entity_id: switch.heating
    - delay: '02:00:00'
    - service: switch.turn_off
      entity_id: switch.heating
    - service: input_boolean.turn_off
      entity_id: input_boolean.heating_boost
