- alias: Heating - Mornings On
  trigger:
    - platform: time
      at: '05:30:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.met_office_temperature
      below: 8
  action:
    - service: switch.turn_on
      entity_id: switch.heating


- alias: Heating - Mornings Off
  trigger:
    - platform: time
      at: '07:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.heating_boost
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.heating


- alias: Heating - Evenings On
  trigger:
    - platform: time
      at: '17:00:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.met_office_temperature
      below: '10'
  action:
    - service: switch.turn_on
      entity_id: switch.heating


- alias: Heating - Evenings Off
  trigger:
    - platform: time
      at: '20:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.heating_boost
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.heating


- alias: Heating - Weekends On
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.met_office_temperature
        below: '10'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.heating


- alias: Heating - Weekends Off
  trigger:
    - platform: time
      at: '15:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.met_office_temperature
        below: '10'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off'
      - condition: state
        entity_id: input_boolean.heating_boost
        state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.heating


- alias: Heating - Boost off
  trigger:
    - platform: state
      to: 'off'
      entity_id: input_boolean.heating_boost
  action:
    - service: switch.turn_off
      entity_id: switch.heating


- alias: Heating - Boost on
  trigger:
    - platform: state
      to: 'on'
      entity_id: input_boolean.heating_boost
  action:
    - service: switch.turn_on
      entity_id: switch.heating
    - delay: '02:00:00'
    - service: switch.turn_off
      entity_id: switch.heating
    - service: input_boolean.turn_off
      entity_id: input_boolean.heating_boost


- alias: Heating - Relight
  trigger:
    - platform: state
      to: 'on'
      entity_id: switch.heating_relight
  action:
    - delay: '00:00:01'
    - service: switch.turn_off
      entity_id: switch.heating_relight


- alias: Heating - Relight Hourly
  trigger:
    platform: time_pattern
    minutes: 5
    seconds: 00
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: time
      after: '05:00:00'
      before: '20:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.heating_relight
    - delay: '00:00:01'
    - service: switch.turn_off
      entity_id: switch.heating_relight
