- alias: Notify - Waste Collection
  trigger:
    - platform: time
      at: '20:00:00'
  condition:
    condition: time
    weekday: thu
  action:
    - service: notify.mobile_app_gef_tactics
      data:
        message: "{{ states.sensor.waste_collection.state }} waste collection is today!"
    - service: notify.mobile_app_lixs_iphone
      data:
        message: "{{ states.sensor.waste_collection.state }} waste collection is today!"
