- alias: Notify - Waste Collection
  trigger:
    - platform: time
      at: '07:16:00'
  condition:
    condition: time
    weekday: fri
  action:
    - service: notify.ios_geoff
      data:
        message: "{{ states.sensor.waste_collection.state }} waste collection is today!"
    - service: notify.ios_lix
      data:
        message: "{{ states.sensor.waste_collection.state }} waste collection is today!"
